---
title: "<b>NCR Report</b>"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document: default
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(htmlwidgets)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}

scottish_councils <- st_read(dsn = "data/geo_data/", layer = "pub_las", quiet = TRUE) %>% st_transform('+proj=longlat +datum=WGS84')

ncr_council_geo <- scottish_councils %>%
  left_join(ncr_council_summary_pop, by=c("local_auth" = "district"))

```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
bins <- c(0, 10, 20, 30, 40, 50, 60, 70, 80)
pal <- colorBin("YlOrRd", domain = ncr_council_geo$devices_per_hundred_thousand, bins = bins)

bins_n <- c(0, 40, 80, 120, 160, 200, 240, 280, 320)
pal_n <- colorBin("YlOrRd", domain = ncr_council_geo$n, bins = bins_n)

labels <- sprintf(
  "<strong>%s</strong><br/>%g Devices per 100,000",
  ncr_council_geo$local_auth, floor(ncr_council_geo$devices_per_hundred_thousand)
) %>% lapply(htmltools::HTML)

labels_n <- sprintf(
  "<strong>%s</strong><br/>%g Total Devices",
  ncr_council_geo$local_auth, floor(ncr_council_geo$n)
) %>% lapply(htmltools::HTML)
```

```{r, message = FALSE}
fig_1 <- leaflet(options = leafletOptions(minZoom = 6)) %>%
  setView(lng = -5, lat = 56, zoom = 6) %>%
  setMaxBounds(lng1 = -1,
               lat1 = 54,
               lng2 = -9,
               lat2 = 63) %>% 
  addProviderTiles(providers$CartoDB.PositronNoLabels) %>% 
  addPolygons(data = ncr_council_geo,
              weight = 1,
              color = "#AFAFAF",
              fillColor = ~pal_n(ncr_council_geo$n),
              fillOpacity = 1,
              label = labels_n,
              highlightOptions = highlightOptions(
                  weight = 2,
                  color = "#5B5B5B",
                  bringToFront = TRUE)) %>% 
  addLegend("bottomleft",
            pal = pal_n,
            values = ncr_council_geo$n,
            title = "Total Devices",
            opacity = 1)
```

```{r, message = FALSE}
fig_2 <- leaflet(options = leafletOptions(minZoom = 6)) %>%
  setView(lng = -5, lat = 56, zoom = 6) %>%
  setMaxBounds(lng1 = -1,
               lat1 = 54,
               lng2 = -9,
               lat2 = 63) %>% 
  addProviderTiles(providers$CartoDB.PositronNoLabels) %>% 
  addPolygons(data = ncr_council_geo,
              weight = 1,
              color = "#AFAFAF",
              fillColor = ~pal(ncr_council_geo$devices_per_hundred_thousand),
              fillOpacity = 1,
              label = labels,
              highlightOptions = highlightOptions(
                  weight = 2,
                  color = "#5B5B5B",
                  bringToFront = TRUE)) %>% 
  addLegend("bottomleft",
            pal = pal,
            values = ncr_council_geo$devices_per_hundred_thousand,
            title = "Devices / 100,000",
            opacity = 1)
```

```{r}
saveWidget(fig_1, file = "maps/fig_1.html")
saveWidget(fig_2, file = "maps/fig_2.html")
```

