---
title: "<b>NCR Report</b>"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document: default
---

```{r}
library(tidyverse)
library(sf)
library(janitor)
library(leaflet)
```

```{r}
ncr_data <- read_csv("data/raw_data/national-charge-point-registry.csv") %>% 
  clean_names() %>%
  filter(charge_device_status == "In service") %>% 
  select(charge_device_id, postcode)
  
postcodes <- read_csv("data/raw_data/scotland_postcodes.csv") %>% 
  clean_names() %>% 
  select(postcode, district)

population <- read_csv("data/raw_data/council-area-profiles-dataset-with-copyright_population-estimates.csv") %>% 
  clean_names()

scottish_councils <- st_read(dsn = "data/geo_data/", layer = "pub_las", quiet = TRUE) %>% st_transform('+proj=longlat +datum=WGS84')

```

```{r}

ncr_council_summary <- ncr_data %>% 
  inner_join(postcodes, "postcode") %>%
  mutate(district = recode(district, "Na h-Eileanan Siar" = "Eilean Siar")) %>% 
  count(district)
  
```

```{r}
population_summary <- population %>%
  filter(year == "2021",
         council_area != "Scotland") %>%
  mutate(council_area = recode(council_area, "Na h-Eileanan Siar" = "Eilean Siar")) %>%
  group_by(council_area) %>% 
  summarise(total_population = sum(population))
```

```{r}
ncr_council_summary_pop <- ncr_council_summary %>% 
  inner_join(population_summary, by=c("district" = "council_area")) %>% 
  mutate(devices_per_hundred_thousand = n / (total_population / 100000))
```

```{r}

ncr_council_geo <- scottish_councils %>%
  left_join(ncr_council_summary_pop, by=c("local_auth" = "district"))

```

```{r}
bins <- c(0, 10, 20, 30, 40, 50, 60, 70, 80)
pal <- colorBin("YlOrRd", domain = ncr_council_geo$devices_per_hundred_thousand, bins = bins)

bins_n <- c(0, 40, 80, 120, 160, 200, 240, 280, 320)
pal_n <- colorBin("YlOrRd", domain = ncr_council_geo$n, bins = bins_n)

labels <- sprintf(
  "<strong>%s</strong><br/>%g Devices per 100,000",
  ncr_council_geo$local_auth, floor(ncr_council_geo$devices_per_hundred_thousand)
) %>% lapply(htmltools::HTML)

labels_n <- sprintf(
  "<strong>%s</strong><br/>%g Total Devices",
  ncr_council_geo$local_auth, floor(ncr_council_geo$n)
) %>% lapply(htmltools::HTML)
```

```{r}
leaflet(options = leafletOptions(minZoom = 6)) %>%
  setView(lng = -5, lat = 56, zoom = 6) %>%
  setMaxBounds(lng1 = -1,
               lat1 = 54,
               lng2 = -9,
               lat2 = 63) %>% 
  addProviderTiles(providers$CartoDB.PositronNoLabels) %>% 
  addPolygons(data = ncr_council_geo,
              weight = 1,
              color = "black",
              fillColor = ~pal(ncr_council_geo$devices_per_hundred_thousand),
              label = labels,
              highlightOptions = highlightOptions(
                  weight = 3,
                  color = "black",
                  bringToFront = TRUE)) %>% 
  addLegend("bottomright",
            pal = pal,
            values = ncr_council_geo$devices_per_hundred_thousand,
            title = "Devices / 100,000",
            opacity = 1)
```

```{r}
leaflet(options = leafletOptions(minZoom = 6)) %>%
  setView(lng = -5, lat = 56, zoom = 6) %>%
  setMaxBounds(lng1 = -1,
               lat1 = 54,
               lng2 = -9,
               lat2 = 63) %>% 
  addProviderTiles(providers$CartoDB.PositronNoLabels) %>% 
  addPolygons(data = ncr_council_geo,
              weight = 1,
              color = "black",
              fillColor = ~pal_n(ncr_council_geo$n),
              label = labels_n,
              highlightOptions = highlightOptions(
                  weight = 3,
                  color = "black",
                  bringToFront = TRUE)) %>% 
  addLegend("bottomright",
            pal = pal_n,
            values = ncr_council_geo$n,
            title = "Total Devices",
            opacity = 1)
```






